Initial implementation
stepchange-tokyo/Stepchange.Automation pull request #1
Opened 2024-07-27 06:18 UTC by davidpbtran

Based on the original SPATPlayerPoints solution created and provided by Michael Belos.

2024-08-01 03:03 UTC, rigelpesit approved these changes
Added some minor comments and suggestions

2024-08-01 03:03 UTC, rigelpesit commented on Spat4.PointsConversion/Services/Spat4ClientFactory.cs
> +        return new Spat4Client(client, account, _options, logger, resiliencePipeline);
Neat trick since you have access to an IServiceProvider is to use ActivatorUtilities:

`ActivatorUtilities.CreateInstance<Spat4Client>(serviceProvider, account, resiliencePipeline);`

You then won't need to pass in logger/options or any other dependencies if you ever add any more dependencies to the `Spat4Client`

2024-08-01 03:03 UTC, rigelpesit commented on Spat4.PointsConversion/appsettings.json
> +    "DailyConversionTime": "08:00",
DailyConversionTimeInJst?

2024-08-01 03:05 UTC, rigelpesit commented on Spat4.PointsConversion/Program.cs
> +builder.Services.AddOptions<Spat4ClientOptions>().Bind(builder.Configuration.GetSection(Spat4ClientOptions.Spat4Client));
Oh and you can also just use `BindConfiguration("Accounts")` no need to get the section

2024-08-02 01:14 UTC, wahid248 requested changes

2024-08-02 01:14 UTC, wahid248 commented on Spat4.PointsConversion/Services/Spat4ClientFactory.cs
> +            AllowAutoRedirect = true,
These 2 properties are `true` by default, we can remove it from the code.
Ref: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=net-8.0

2024-08-02 01:15 UTC, wahid248 approved these changes

2024-08-02 01:24 UTC, wahid248 approved these changes

2024-08-02 01:24 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +internal class PointConversionService(IOptions<PointConversionServiceOptions> serviceOptions, IOptions<List<Account>> accounts, TimeProvider timeProvider, Spat4ClientFactory clientFactory, ILogger<Po
No `IDisposable`?

2024-08-02 01:24 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +                }
We can perhaps NOT `await` this logout call, that can make the process faster, since we are returning the method after this call anyway

2024-08-02 03:45 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +    }
Resolving this comment as Rigel made the same comment above
https://github.com/stepchange-tokyo/Stepchange.Automation/pull/1#discussion_r1699309544

2024-08-02 03:46 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +        _stoppingCts = new CancellationTokenSource();
Resolving this comment since Rigel has made the same comment above
https://github.com/stepchange-tokyo/Stepchange.Automation/pull/1#discussion_r1699309544

2024-08-02 03:57 UTC, wahid248 approved these changes

2024-08-02 03:57 UTC, wahid248 commented on Spat4.PointsConversion/Services/Spat4Client.cs
> +        await Task.Delay(Random.Shared.Next(_options.MinPageRequestWaitTimeInMilliseconds, _options.MaxPageRequestWaitTimeInMilliseconds));
If we have a delay for each Http request, do we need anymore delays in other places of the codebase?

2024-08-02 03:57 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +                await Task.Delay(conversionStartDelay, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
I'm curious why we are suppressing throwing here? Since the `Delay` task is taking in the `cancellationToken`, it will throw a `TaskCanceledException` when the token is triggered. So if we are suppressing the throw, the thread will simply continue the rest of the code.

2024-08-02 03:57 UTC, wahid248 commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +                await Task.Delay(conversionStartDelay, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
On a second note, since we are using the `ConfigureAwaiter` here, it will capture the thread context as a default behavior. But we are waiting for 12-15 seconds here which is a long time. So its probably better to let the thread pool handle the context, which will make the code look like:
`await Task.Delay(conversionStartDelay, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None);`

Ref: https://blog.stephencleary.com/2023/11/configureawait-in-net-8.html#:~:text=options%20in%20turn.-,ConfigureAwaitOptions.None,-and%20ConfigureAwaitOptions.ContinueOnCapturedContext

2024-08-07 02:45 UTC, davidpbtran commented on Spat4.PointsConversion/Program.cs
> +builder.Services.AddOptions<Spat4ClientOptions>().Bind(builder.Configuration.GetSection(Spat4ClientOptions.Spat4Client));
We could but not implementing as I don't think there is any negative effect from leaving this. 
Will keep in mind the `BindConfiguration("Accounts")` advice for next time though!

2024-08-07 02:46 UTC, davidpbtran commented on Spat4.PointsConversion/Program.cs
> +.WithName("GetPointConversionStatus")
Yes I believe eventually there will be an API that can be used to check the status of the accounts and conversions. The current app has a UI which displays the status but we don't have a frontend yet. If/when we do, we'll be updating this API to provide the necessary data

2024-08-07 03:00 UTC, davidpbtran commented on Spat4.PointsConversion/Program.cs
> +builder.Services.AddOptions<Spat4ClientOptions>().Bind(builder.Configuration.GetSection(Spat4ClientOptions.Spat4Client));
I changed everything to BindConfiguration due to OCD

2024-08-07 03:10 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +        _stoppingCts = new CancellationTokenSource();
Done, thanks.

2024-08-07 03:11 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +    private Timer? _timer;
Done.

2024-08-07 03:14 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +            _ = ConvertPoints(cancellationToken);
Cool thanks. This also enables me to use new `new Timer(callback) + `Timer.Change` combo as well since I no longer need to pass a token around.

2024-08-07 03:19 UTC, davidpbtran commented on Spat4.PointsConversion/Services/Spat4ClientFactory.cs
> +        return new Spat4Client(client, account, _options, logger, resiliencePipeline);
Oh that's sick so I'm assuming the logger and options injection will be handled by the DI framework as normal?

I could probably do all of the ResiliencePipeline resolution within the client itself as well then

2024-08-07 03:19 UTC, davidpbtran commented on Spat4.PointsConversion/appsettings.json
> +    "DailyConversionTime": "08:00",
Good shout. Done.

2024-08-07 03:22 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +    }
Fixed

2024-08-07 03:22 UTC, davidpbtran commented on Spat4.PointsConversion/Services/Spat4ClientFactory.cs
> +            AllowAutoRedirect = true,
Yeah I know, I just copied this directly from the existing code. Removed anyway, cheers.

2024-08-07 03:36 UTC, davidpbtran commented on Spat4.PointsConversion/Services/Spat4ClientFactory.cs
> +        return new Spat4Client(client, account, _options, logger, resiliencePipeline);
Done

2024-08-07 03:40 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +internal class PointConversionService(IOptions<PointConversionServiceOptions> serviceOptions, IOptions<List<Account>> accounts, TimeProvider timeProvider, Spat4ClientFactory clientFactory, ILogger<Po
You were right about this actually! Fixed, thanks

2024-08-07 03:46 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +                }
Sounds good. Looking at the original code more closely, the process is already "complete" before logging out so I've moved `_ = client.LogoutAsync()` to the bottom.

2024-08-07 03:48 UTC, davidpbtran commented on Spat4.PointsConversion/Services/Spat4Client.cs
> +        await Task.Delay(Random.Shared.Next(_options.MinPageRequestWaitTimeInMilliseconds, _options.MaxPageRequestWaitTimeInMilliseconds));
Yes based on the original business logic. There are separate delays for starting the conversion process for each account, between each conversion round, plus between each http request.

2024-08-07 04:02 UTC, davidpbtran commented on Spat4.PointsConversion/Services/PointConversionService.cs
> +                await Task.Delay(conversionStartDelay, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
You're right about not using `SuppressThrowing` here. We don't want it to continue processing after a cancellation. However this issue isn't related to the thread context.

The intent was to allow graceful shutdown of the service. If we allow an unhandled TaskCanceledException to be thrown here, then the app will crash. 

To handle this I have wrapped the whole method in a try catch and I'm catching the TaskCanceledException and then simply writing a log.

We could take it a step further and pass the cancellation token all the way down into the Http calls... but 😁

2024-08-08 02:59 UTC, merged